---
squid-docker:
  script:
  - cd squid
  - docker build -t $CI_REGISTRY/eidas/test-environment/squid:latest
  - docker push $CI_REGISTRY/eidas/test-environment/squid:latest
  only:
    changes:
    - squid/*
