---
apiVersion: v1
data:
  RESOURCES_PW: 7l8XNiA3
  RESOURCES_SCHEMA: signing
  RESOURCES_URL: 'jdbc:postgresql://postgresql:5432/bosa_fts_ta'
  RESOURCES_USER: testuser
  SIGNING_PW: 7l8XNiA3
  SIGNING_SCHEMA: signing
  SIGNING_URL: 'jdbc:postgresql://postgresql:5432/bosa_fts_ta'
  SIGNING_USER: testuser
  READY_MARKFILE: '/tmp/lotl.ready'
kind: ConfigMap
metadata:
  name: databaseconfig
  namespace: bosa-trust-services
---
apiVersion: v1
data:
  PROXY_HOST: squid
  PROXY_NONPROXYHOST: localhost
  PROXY_PORT: '3128'
kind: ConfigMap
metadata:
  name: httpproxysettings
  namespace: bosa-trust-services
---
apiVersion: v1
data:
  CORS_ALLOWED_ORIGINS: 'http://localhost:3000,https://sign.local.test.belgium.be,https://idp.local.test.belgium.be'
  KEYSTORE_ENABLED: "true"
  TSA_MOCK: "true"
  S3ENDPOINT: http://minio:9000/
  S3ACCESSKEY: minioadmin
  S3SECRETKEY: minioadmin
  S3SECRETBUCKET: secrets
kind: ConfigMap
metadata:
  name: signvalidationsettings
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: idpconfig
data:
  SIGNING_URL: "http://signvalidation-svc.bosa-trust-services.svc.cluster.local/"
  HSM_MODULE: "/usr/lib/softhsm/libsofthsm2.so"
  HSM_USER_PIN: "12345"
  HSM_KEY_ID: "test_IdP"
  HSM_SLOT: "0"
  IDP_URL: "https://fas.url"
  FAS_CERTIFICATE_FILENAME: "/etc/config/fas.pem"
  REQUIRE_SIGNED_REQUEST: 'false'
  FAS_CLIENT_ID: "IAMFAS"
  CORS_ALLOWED_ORIGINS: 'http://localhost:3000,https://idp.local.test.belgium.be'
