---
apiVersion: v1
data:
  RESOURCES_PW: 7l8XNiA3
  RESOURCES_SCHEMA: signing
  RESOURCES_URL: 'jdbc:postgresql://postgresql:5432/bosa_fts_ta'
  RESOURCES_USER: testuser
  SIGNING_PW: 7l8XNiA3
  SIGNING_SCHEMA: signing
  SIGNING_URL: 'jdbc:postgresql://postgresql:5432/bosa_fts_ta'
  SIGNING_USER: testuser
kind: ConfigMap
metadata:
  name: databaseconfig
  namespace: bosa-trust-services
---
apiVersion: v1
data:
  PROXY_HOST: squid
  PROXY_NONPROXYHOST: localhost
  PROXY_PORT: '3128'
kind: ConfigMap
metadata:
  name: httpproxysettings
  namespace: bosa-trust-services
---
apiVersion: v1
data:
  CORS_ALLOWED_ORIGINS: 'http://localhost:3000,https://sign.in.testing/'
  KEYSTORE_ENABLED: "true"
kind: ConfigMap
metadata:
  name: signvalidationsettings
