---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresdata
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  serviceName: "postgresql"
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:latest
        env:
        - name: PGDATA
          value: "/var/lib/postgresql/data/db"
        - name: POSTGRES_USER
          value: "testuser"
        - name: POSTGRES_DB
          value: bosa_fts_ta
        - name: POSTGRES_PASSWORD
          value: ""
        - name: POSTGRES_HOST_AUTH_METHOD
          value: "trust"
        ports:
        - containerPort: 5432
          name: postgresql
        volumeMounts:
        - mountPath: "/var/lib/postgresql/data"
          name: "postgresdata"
      volumes:
      - name: "postgresdata"
        persistentVolumeClaim:
          claimName: "postgresdata"
