apiVersion: v1
kind: Template
metadata:
  name: container-squid
  labels:
    name: squid
  annotations:
    description: Template for squid
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: squid
  spec:
    replicas: 1
    selector:
      deploymentconfig: squid
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 100%
        maxUnavailable: 0%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          application: squid
          deploymentconfig: squid
      spec:
        containers:
        - image: registry-fsf.services.belgium.be:5000/eidas/test-environment/squid:latest
          imagePullPolicy: Always
          name: squid
          port: 3128
          resources:
            limits:
              cpu: 1000m
              memory: 1024Mi
            requests:
              cpu: 50m
              memory: 64Mi
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: Squid proxy service
    name: squid
  spec:
    ports:
    - name: squid-cache
      port: 3128
      protocol: TCP
      targetPort: 3128
    selector:
      deploymentconfig: squid
