#!/bin/sh

if [ ! -d /var/spool/squid/00 ]; then
	echo "Initializing cache..."
	$(which squid) -N -f /etc/squid/squid.conf -z
fi
echo "Starting squid..."
exec $(which squid) -f /etc/squid/squid.conf -NYCd 1 "$@"
