#!/bin/sh

if [ -f /etc/config/allowed_urls ]; then
	# allow all
	echo "http_access allow localnet" > /etc/squid/conf.d/acls.conf
else
	echo 'acl allowedsites dstdomain "/etc/config/allowed_urls"' > /etc/squid/conf.d/acls.conf
	echo 'http_access allow allowedsites' >> /etc/squid/conf.d/acls.conf
fi

if [ ! -d /var/spool/squid/00 ]; then
	echo "Initializing cache..."
	$(which squid) -N -f /etc/squid/squid.conf -z
fi
echo "Starting squid..."
exec $(which squid) -f /etc/squid/squid.conf -NYCd 1 "$@"
